version: "3.9"
services:
  grafana:
    image: grafana/grafana:10.4.2
    container_name: aptoscope_grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "${GF_ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_ADMIN_PASS:-admin}"
      GF_INSTALL_PLUGINS: "frser-sqlite-datasource,grafana-piechart-panel"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - ./mock:/data
    restart: unless-stopped
